### ISSUE TITLE
Extract Vector tile algorithm in a separate library (in other repository)

### ISSUE THREAD

**Issue by rrequero** [GlobalFishingWatch/pelagos-client#197]
We need can added the vectortile algorithm that it transform the binary tile to Array of Javascript in the new application. 
Need that the library implements the npm standard library. 
It is necessary that the library is implemented in vanillajs (no frameworks or without visualization libraries) because only use it to convert the server response (binary) in an array of javascript.
Thanks

**Comment by enriquetuya** [comment]
@rrequero I think on a first phase we could use the branch on pelagos-client (https://github.com/SkyTruth/pelagos-client/tree/libraryification) directly with the AMD modules. And then move to a separate repo once everything is tested. You should be able to use npm pointing to the github branch and then use webpack. I'm assigning @andres-arana so he can provide more details.

**Comment by redhog** [comment]
This has been implemented (all parts can now be loaded individually using requirejs or some other amd loader).
