### ISSUE TITLE
Return promise instead of events (Vectortile library)

### ISSUE THREAD

**Issue by rrequero** [GlobalFishingWatch/pelagos-client#198]
If is possible, we need that the vectortile library returns a promise object when we execute the principal function. And when the algorithm will finish,it resolves the promise with the result data.

Thanks

**Comment by enriquetuya** [comment]
@rrequero for the first iterations I think that it is worth doing the translation of events to promises on the client side. If we see that everything works and the performance gets affected then we should see of implementing promises on the library itself.

I'm assigning to @andres-arana  so he can provide you some docs of how to translate events to promises.

**Comment by andres-arana** [comment]
We moved out of this approach of sharing code between the new client and the old one, so I'm closing this ticket.
