### ISSUE TITLE
0.20 // Expose torque layer time slider

### ISSUE THREAD

**Issue by redhog** [GlobalFishingWatch/pelagos-client#216]
Make the torque layer time slider visible on a branch

Related to https://github.com/SkyTruth/pelagos-server/issues/1084

**Comment by redhog** [comment]
This is implemented on a branch, _not_ meant for merging into master/devel/release: https://github.com/SkyTruth/pelagos-client/tree/216-visible-torque

**Comment by enriquetuya** [comment]
@redhog why is this intended not to be merged? Was this something that you talked with Paul last Friday? What was the idea? Where should it be deployed?

Couldn't we make the change only to be displayed on the editing sidebar so we can merge it?

**Comment by redhog** [comment]
This is a hack for testing purposes. Making it only display sometimes would be way more work, and I'd only want to do that if it was actually to be used in production. But this is just to be able to evaluate torque layers and their capabilities properly, to decide if we're actually going to use them.

**Comment by enriquetuya** [comment]
@redhog who is intended to use this branch for testing? @pwoods25443 requested this?

**Comment by redhog** [comment]
Yes, and he's the one who needs it

**Comment by enriquetuya** [comment]
@pwoods25443 what was your plan for this change?
