### ISSUE TITLE
Heatmap should change to points when you zoom in far enough

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/pelagos-client#231]
Make a parameter in the workspace that specifies a zoom level where you change the way you draw the heatmap to draw solid points for every point with a weight greater than some value.

**Comment by redhog** [comment]
Ping @pwoods25443 is this the effect you wanted? Note the new slider "heatmap_zoom" for the ClusterAnimation, in the editing sidebar.

**Comment by enriquetuya** [comment]
@redhog Based on our call, lets make the default behaviour to be disabled but that can be changed by the editing sidebar.

**Comment by enriquetuya** [comment]
@pwoods25443 you can try this out here: 
http://alpha-dev.globalfishingwatch.org/viz?workspace=/workspace/benthos-pipeline-699-tileset-f
go to the editing sidebar, open the fishing effort and modify the value for `heatmap_zoom` by default it is disabled.

![points](https://cloud.githubusercontent.com/assets/355597/17741956/8c33b376-6474-11e6-8a35-1f91f72a5da8.png)

**Comment by pwoods25443** [comment]
Hmm - that does not work very well.  I think we need to look at filtering the heatmap to only contain points with weight > 0.5 before clustering if we're going to do this.  We don't want to end up highlighting all the non-fishing points that end up in there.

**Comment by pwoods25443** [comment]
@redhog when I adjust the heapmap zoom value so that more points are displayed, I can't shift click on any of them.  I can only shift click on the ones that are displayed before I adjust heatmap zoom.  Why is this?

**Comment by redhog** [comment]
@pwoods25443 That's because I probably screwed up the implementation of this feature in the mouseover shader code... The same thing needs to happen both in the normal shader code and the mouse over shader.

**Comment by enriquetuya** [comment]
Deploying to beta2 to test it out.

**Comment by pwoods25443** [comment]
@redhog playing around with this a little more, I think that we want to make a gradual transition over 2 or 3 zoom levels from pure heatmap to solid points.  The current implementation is too dramatic a change for one zoom level.

 The way we could do this is to have a minimum point radius and step it up from 0 to MAX 

For instance, for zoom levels 0 to 7 we display the heatmap as usual
For level 8 we set the minimum point size to MAX/2
For level 9 we set the minimum point size to MAX

Do you think there is way to do this when we generate the tiles just by manipulating weight and sigma for tiles at the right zoom level or with the right vessel density?  Like just have a minimum weight and sigma value?

**Comment by redhog** [comment]
You could fake it with weight and sigma, but that gets complicated, so I'd recommend not to. But having a minimum that changes depending on zoom level is doable. However, the exact details might be really hard to get right so it looks good. Prepare for some experimentation time on this.

**Comment by enriquetuya** [comment]
@pwoods25443 we are having some questions from users that see dots on a global zoom level, but when they zoom in they stop seeing the fishing dots (they could if they use the intensity slider, but they do not). What do you think of enabling this feature as is? I know the transition is a bit harsh but it would solve the issue we are having.

Vizz map could keep on working on this issue on the future.

**Comment by pwoods25443** [comment]
Closing this in favor of the new vizzuality UI
