### ISSUE TITLE
Test client on tablet

### ISSUE THREAD

**Issue by redhog** [GlobalFishingWatch/pelagos-client#243]
- Pinch zoom
- Click on stuff

**Comment by enriquetuya** [comment]
@redhog please go ahead and test this out on your ipad.
On @pwoods25443 ipad pro it looks like the following:
![ipad pro with chrome](https://cloud.githubusercontent.com/assets/355597/17903827/441fdfaa-6943-11e6-915a-8851c977fd01.jpg)

**Comment by redhog** [comment]
- [ ] Color picker hue picker moves to strange position when clicked and moved on Nexus 9
- [x] Need to set meta tags to not zoom whole page
- [x] ~~Impossible to click/edit the start/end dates in the timeslider~~
  - Paul says it should be this way because on tablets we want to avoid the keyboard
