### ISSUE TITLE
Better message on cluster select

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/pelagos-client#288]
When the user clicks on a cluster in the heatmap, it opens the vessel info tab in the sidebar and displays 'Cluster Selected'

This message should be more informative.   Perhaps it could say something like:

`There are multiple vessesls at this location.  Zoom in on the map some more`

<img width="270" alt="global_fishing_watch" src="https://cloud.githubusercontent.com/assets/2694181/18095247/57645468-6ea4-11e6-94c8-779784f7e580.png">

**Comment by redhog** [comment]
Maybe display the number of vessels in the cluster? We do have that information...

**Comment by pwoods25443** [comment]
@redhog yeah it would be nice to be able to tell them something about the cluster, but failing that we should at least tell them that they need to zoom in

**Comment by redhog** [comment]
Ok, so we don't have that data for now. We have weight and sigma, not count :/
