### ISSUE TITLE
Upload 3 icons to GFW blog server

### ISSUE THREAD

**Issue by jarmstrongbts** [GlobalFishingWatch/pelagos-client#292]
Please upload the following 3 icons to the blog server :
- http://beta2.globalfishingwatch.org/2173f2478013bc6fa091b1cdb2a6926b.svg (email)
- http://beta2.globalfishingwatch.org/9d0a23199dbbc2ab7fdab49adeca9d71.svg (twitter)
- http://beta2.globalfishingwatch.org/6632b58184d4c207ca024e2436d553c0.svg (facebook)
- http://beta2.globalfishingwatch.org//1903c0924a47592577a26e72c4f300ac.svg (mobile menu)
- http://beta2.globalfishingwatch.org/bbebaa118c9b3ac4adcd377dd1562ae3.svg (ldf logo)

To this folder: 

/wp-content/uploads/2016/09/

**Comment by jarmstrongbts** [comment]
Added one more icon, for the mobile menu, also LDF logo.

**Comment by enriquetuya** [comment]
@jarmstrongbts The URLs on the description of the ticket are all blank.

**Comment by enriquetuya** [comment]
@jarmstrongbts Done. Moved to `wp-content/uploads/2016/09`
Name of the files are:

```
  email.svg
  facebook.svg
  idf_logo.svg
  mobile_menu.svg
  twitter.svg
```
