### ISSUE TITLE
Rearrange buttons/Create new map zoom buttons

### ISSUE THREAD

**Issue by jarmstrongbts** [GlobalFishingWatch/pelagos-client#310]
- move time zoom buttons to center of time window - DONE
- larger play button at left of time slider
- move share button (above time slider?)

**Comment by pwoods25443** [comment]
@jarmstrongbts if you put "Closes #310" in the description of the PR, this it will automatically close the issue when the PR is merged.   Otherwise you need to close it manually.  If this issue is done, then please go ahead and close it.
