### ISSUE TITLE
Timeslider zoom in/out buttons cover window start/end dates and prevent edit

### ISSUE THREAD

**Issue by pwoods25443** [GlobalFishingWatch/pelagos-client#321]
The div that contains the timeslider is 100% width and covers the time window start and end dates.  This intercepts the mouse click and prevents the user for editing the dates.

<img width="696" alt="developer_tools_-_http___ui_prod_globalfishingwatch_org_map_workspace_pelagos-api-0b57d944-83a0-4b25-9fa2-41ae446cc716" src="https://cloud.githubusercontent.com/assets/2694181/18420256/3bdbbd20-783c-11e6-928d-59c056353a1c.png">

<img width="1232" alt="developer_tools_-_http___ui_prod_globalfishingwatch_org_map_workspace_pelagos-api-0b57d944-83a0-4b25-9fa2-41ae446cc716_and_global_fishing_watch_-_map_workspace_pelagos_api-0b57d944-83a0-4b25-9fa2-41ae446cc716" src="https://cloud.githubusercontent.com/assets/2694181/18420274/7e8c5102-783c-11e6-81e7-a5bc66066a6c.png">

**Comment by jarmstrongbts** [comment]
PR for this fix is here:
https://github.com/GlobalFishingWatch/pelagos-client/pull/322
