### ISSUE TITLE
Avoid scrolling the map below the world

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/pelagos-client#343]
Right now you are allowed to drag the map below the world, cartoDB starts sending 404 due to this issue. 
![avoid_drag](https://cloud.githubusercontent.com/assets/355597/18591045/68eb0676-7c07-11e6-8153-fc5a1de3333e.gif)

**Comment by redhog** [comment]
http://code.google.com/p/gmaps-api-issues/issues/detail?id=750
http://stackoverflow.com/questions/3125065/how-do-i-limit-panning-in-google-maps-api-v3

**Comment by enriquetuya** [comment]
@redhog this is still happening with your code change. Please try it out on dev.globalfishingwatch.org.
