### ISSUE TITLE
Feature request: area inspector

### ISSUE THREAD

**Issue by redhog** [GlobalFishingWatch/pelagos-client#346]
- [x] Select a rectangle
  - Get list of seriesgroups
- [x] Add animations for each vessel track
  - [x] Set name to vessel name
  - [ ] Originally set to hidden
  - [x] Do info query to get names
- ~~[ ] Display vessel track animations in a separate blade in the sidebar ("Vessel tracks"? Better more generic name?)~~ Moved to separate ticket
- [x] Info icon displays vessel info from /info

**Comment by redhog** [comment]
Connects https://github.com/GlobalFishingWatch/pelagos-client/issues/348

**Comment by redhog** [comment]
Should we use https://developers.google.com/maps/documentation/javascript/examples/user-editable-shapes or a webgl rectangle? Mouse interaction might be easier with webgl, but we have to code more ourselves.

**Comment by enriquetuya** [comment]
@redhog this was on the backlog. Please work on the Ready tickets first.

**Comment by enriquetuya** [comment]
@redhog please resolve the conflicts on the PR (https://github.com/GlobalFishingWatch/pelagos-client/pull/384) so I can merge it. I've tested locally and works well enough. I'm doing a separate ticket with improvements to work on next week.

**Comment by enriquetuya** [comment]
@redhog we need to:
- [x] 404s when selecting an area. Detail here: https://github.com/GlobalFishingWatch/GFW-Issues/issues/2
- [x] Draw the rectangle on top of ALL animations, righw now the rectangle is drawn below the heatmap, which is very difficult to see.
- [ ] Increase the width of the border and make it white, the black one makes it difficult to see on both bathimetry layer and regular view. 
  - Not sure white works very well.
    - You can experiment with the color yourself here: https://github.com/GlobalFishingWatch/pelagos-client/blob/devel/js/app/Visualization/Animation/BboxSelection-fragment.glsl#L4
    - You can experiment with the width here (there is a graphics card specific upper limit!): https://github.com/GlobalFishingWatch/pelagos-client/blob/devel/js/app/Visualization/Animation/BboxSelection-vertex.glsl#L7
- ~~[x] Could it be possible to fill the rectangle with a color with alpha?~~
  - No.
