### ISSUE TITLE
Welcome pop-up

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/pelagos-client#369]
# We want to have a pop-up on the site that displays some hints and information about the site. The message should be an html that gets updated when we do the deploy of the site. So it should be possible to send a url as a parameter.

The pop-up will look like the following:

![help_mock1](https://cloud.githubusercontent.com/assets/355597/18887115/3183a042-84c9-11e6-8132-46a656cea329.jpg)

The user should see the pop-up on **ANY** workspace link he opens, unless he/she has clicked on `Don't show me this message unless new features are available.`

In Case the user has clicked on `Don't show me this message unless new features are available.`, the message will not be displayed until the next version of the html is uploaded to the site. This could be achieved by sending an explicit version number or a convention on the welcome pop-up html filename.

We need:
- [x] Make it possible that the welcome pop-up message is configured using a url on the `config.json`
- [x] Make it possible that the user can disable the pop-up until a new version is uploaded.
- [x] Make it possible to trigger the pop-up at any time, maybe `ctrl + alt + w`
- [x] Document on the repo documentation how it works.

Note: This has similarities to the changes implemented here: https://github.com/GlobalFishingWatch/pelagos-client/tree/6a3909fda8ecc7122693e0f68c71048e67871970

**Comment by enriquetuya** [comment]
@redhog the functionality itself works great but we need the styles to match the ones on the mock provided by Johnna:

https://cloud.githubusercontent.com/assets/355597/18887115/3183a042-84c9-11e6-8132-46a656cea329.jpg

Also we need to align the `don't display again` message with the close button:

![selection_013](https://cloud.githubusercontent.com/assets/355597/19050705/35c1f07a-8986-11e6-880a-601d46726e4f.jpg)

**Comment by enriquetuya** [comment]
Setting as blocker since this is needed for the current sprint.

**Comment by redhog** [comment]
@enriquetuya @jarmstrongbts Including the blue background? That does not match the dialog styling in the rest of the app. Would you like to:
- Make yet another special case
- Change the styling of all dialogs
- Apply the current dialog colors to this dialog too

Also, could you send me the html for the message in Johnnas dialog example? Most of this is about in-line styles that needs to be applied in the html content of message.html (or whatever you chose to call that file).

**Comment by enriquetuya** [comment]
@redhog let's fix the vertical alignment, and leave the styles for a new ticket for the next sprint.

![35c1f07a-8986-11e6-880a-601d46726e4f](https://cloud.githubusercontent.com/assets/355597/19078958/56baccbe-8a28-11e6-8a4c-8280e8929e36.jpg)

**Comment by enriquetuya** [comment]
@redhog is it possible to display the message pop-up before any of the other layers starts to get loaded? Check how it is working now:

![ezgif-3519188742](https://cloud.githubusercontent.com/assets/355597/19089009/ebc68610-8a4e-11e6-9164-314455e77610.gif)

**Comment by enriquetuya** [comment]
@redhog on the ipad, the pop-up is being deisplayed always, no matter you set the `don't show again` (check it yourself) and @vaiduke2 reported on windows Chrome, that after she close the browser and opens it again the message is displayed again also.

You can try it out here: http://dev.globalfishingwatch.org/map

**Comment by redhog** [comment]
http://storage.googleapis.com/world-fishing-827/pelagos/components/client/release-0.26-20161005143510UTC/embedded.html?headers=%7B%22Authorization%22%3A%22Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InNmOmh0dHBzOi8vdGVzdC5zYWxlc2ZvcmNlLmNvbS9pZC8wMEQ2MzAwMDAwMDh3YldFQVEvMDA1NjMwMDAwMDBqVTVSQUFVIiwiaWF0IjoxNDc1MjQzMDE2fQ.WYpNZFg6l3qkDnyOuoEp_gDBB5ZUr5cU5GN5O7gCmWE%22%7D&workspace=https%3A%2F%2Fapi-dot-skytruth-pleuston.appspot.com%2Fv1%2Fworkspaces%2Fvizzuality-gfw-integration-dev-final-v4.json

**Comment by redhog** [comment]
* Unable to reproduce on iPad (A1455)
  * However, cookie does not persist over a reboot of the device
* Unable to reproduce on Windows Chrome

**Comment by redhog** [comment]
The bug had nothing to do with environment - the cookie was set to session only.

**Comment by enriquetuya** [comment]
@redhog the error keeps happening on ios-safari. Please try `dev.globalfishingwatch.org` on that device.

**Comment by enriquetuya** [comment]
@redhog as we discussed on our call on Friday, please check how `dev.globalfishingwatch.org` welcome pop-up works on your Mac Safari, to see if we have the same issue as on iOS device.

Open the url, check the `don't close`, close safari, and open it again.

For other debugging methods check here: https://github.com/SkyTruth/pelagos-server/issues/1208#issuecomment-252340432

**Comment by redhog** [comment]
The error does not happen on MacOS Safari.

**Comment by redhog** [comment]
Going to buy the components from this howto: http://www.gottabemobile.com/2014/08/28/how-to-connect-an-ipad-to-ethernet/

**Comment by enriquetuya** [comment]
I'll create a separate ticket for the bugs. I'll be adding the new text on the deploy repo:

```
Welcome! You are seeing a heat map of fishing activity across the globe. 
Adjust the time period you are viewing with slider at the bottom of the screen by clicking/dragging the beginning and end points. 
Zoom in and out with the plus/minus signs in the upper left hand corner.
Click on a point on the heat map to reveal a vessel track.
For additional help getting started, view our video tutorial video here. << links to the video tutorial >>
For frequently asked questions, review FAQs here. << links to the FAQ page >>
```
