### ISSUE TITLE
Changes for multiple vessel functionality

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/pelagos-client#391]
In order to release the changes on  https://github.com/GlobalFishingWatch/pelagos-client/issues/348 we would like to have some changes:
- [x] We need that instead of `Vessel Track` the layer is named like the vessel that was saved and if that data is not present use the series_group value.
- [ ] Vessel Track layer should have an information pop-up that has the details of the vessel. Will be done on (https://github.com/GlobalFishingWatch/pelagos-api/issues/77)
  - [ ] The labels should read `Vessel name` instead of `vesselname`, `MMSI` instead of `mmsi`, `IMO` instead of `imo`, `Callsign` instead of `callsign`. 
  - [ ] The order of the information on the vessel pop-up should be the following: `Vessel Name`, `MMSI`, `Callsign`, `IMO`, `FLAG`. We don't want to display series and series group there. 
- [x] Change the save icon with a `pin` the users are more used of having the `pin` in all platforms as a way of retaining some information no matter what. 

Nice to have:
- [x] Add ability to change the vessel name.
- [x] Add color picker to each vessel track on configuration mode, like the fishing layer. Change both the HIGH and LOW to the same value.

**Comment by redhog** [comment]
Popup content is related to https://github.com/GlobalFishingWatch/pelagos-api/issues/70 and the move of rendering of hardcoded popup stuff to pelagos-api. This very specific ordering and naming of fields should never have been a client issue to begin with.

**Comment by redhog** [comment]
Changing the layer name is possible in edit mode. Just click the title and change it.

Question: When no vessel info is available, could we use the series_group value, rather than the index, since that won't get messy if you add and remove multiple layers many times (the same vessel always have the same number)?

**Comment by redhog** [comment]
As for the color picker, should it set the high and low values to the same value?

**Comment by enriquetuya** [comment]
@redhog I've updated the description.

**Comment by enriquetuya** [comment]
@redhog 
- [x] the PR has conflicts: https://github.com/GlobalFishingWatch/pelagos-client/pull/393

```
Conflicting files
js/app/Data/Selection.js
```
- [ ] Add `text-overflow: ellipsis;` to the layer name so this does not happen: 

![image](https://cloud.githubusercontent.com/assets/355597/19485508/bf530926-9531-11e6-88da-eb633f9db40e.png)

**Comment by redhog** [comment]
I have fixed the conflict. The ellipsis doesn't work due to the dom strcuture and styling of other elements - the animation-title never gets its size restricted, and it's not possible to (easily) do that. If we reworked the styles and used display: table-cell, maybe... I suggest making the sidebar just ever so much wider by default...

**Comment by enriquetuya** [comment]
@redhog The PR is still in conflict, I think it is due to the latest Categorized Blade merge. 
- [x] Fix conflicts: https://github.com/GlobalFishingWatch/pelagos-client/pull/393
- [x] Make the sidebar a bit wider to avoid the issue, based on your suggestion. Don't make it too wider, just to avoid the issue.

**Comment by redhog** [comment]
Merged
