### ISSUE TITLE
Make only the titles of the blades on the side menu UPPERCASE

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/pelagos-client#394]
Based on https://github.com/GlobalFishingWatch/GFW-Tasks/issues/312

We need to remove the UPPERCASE from everywhere except the BLADES Title on the side menu.

**Comment by enriquetuya** [comment]
@redhog 
- [x] right now the only title that is uppercase is the one on the selected blade, we want all blade titles to be uppercase, no matter if they are selected or not.
  
  ![selection_043](https://cloud.githubusercontent.com/assets/355597/19584967/e1347acc-971e-11e6-9099-1f5b8f5d65dd.jpg)
- [ ] `flags` filter label should be `Flag`

![selection_044](https://cloud.githubusercontent.com/assets/355597/19585006/45c85d5a-971f-11e6-9390-0bf190183247.jpg)

**Comment by redhog** [comment]
The "flags" title is taken from the selection name in the workspace, see https://github.com/GlobalFishingWatch/pelagos-client/blob/devel/js/app/Visualization/UI/FilterViewer.js#L45

Here is a workspace excerpt for how this is controlled - I've changed flags to Flags:

```
{
    "map": {
        "animations": [
            {
                "args": {
                    "columns": {
                        "filter": {
                            "name": "filter",
                            "source": {
                                "_": null,
                                "Flags": -1,
                                "timerange": -1
                            },
                            "type": "Float32"
                        }
                    },
                    "selections": {
                        "Flags": {
                            "data": {"category": [{"__jsonclass__": ["Number","-Infinity"]},{"__jsonclass__": ["Number","Infinity"]}]},
                            "header": {"length": 2},
                            "max_range_count": 10,
                            "sortcols": ["category"]
                        }
                    }
                }
            }
        ],
    }
}
```

Notes:
- The term "Flags" shows up in two places: The selection name, and the filter column that uses this selection to filter points on the map. These two obviously have to match.
- You can add more selections like the Flags one, and just add them to the "source" structure of the filter column. The selection filters will be ANDed together. We could for example add both flagstate and gear type as selections, and you could then filter to only show Chineese trawlers. 
- "category" is the name of the source column in the tiles, which should possibly be renamed "flags" too for better documentation at some point.
