### ISSUE TITLE
Edit workspace as text

### ISSUE THREAD

**Issue by redhog** [GlobalFishingWatch/pelagos-client#413]
Connects https://github.com/GlobalFishingWatch/pelagos-api/issues/94

Let the user edit the workspace JSON (prettyfied) directly. Load the modified workspace into the current client and/or save it, possibly with a user chosen name.

**Comment by enriquetuya** [comment]
@redhog check my comment here: https://github.com/GlobalFishingWatch/pelagos-client/pull/430/files#r94341219

**Comment by enriquetuya** [comment]
@redhog the new key binding  is up to you. Use any key combination that we are not using now. It will be hidden in the shortcut pop-up help on prod, so just for internal use.

**Comment by redhog** [comment]
CTRL-ALT-R
