### ISSUE TITLE
Add support for another map layer different than google maps

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/pelagos-client#440]
We want to support a different map layer. We are considering http://leafletjs.com/ and https://openlayers.org/, leaflet seems to have more configuration options and seems to be more similar to google maps so it seems to be the bets fit. 

The goal is to support a better offline mode and be able to run pelagos client on countries where google is blocked. 

* [ ] Define JS library to use leafletjs or openlayers. 
* [ ] Load basemap. Carto? (if leaflet or openlayers support it) 

We need to serve a very basic basemap that you need to differenciate countries/sea, something like this:
![basemap](https://user-images.githubusercontent.com/355597/27185965-56353290-51bd-11e7-89d7-ad29b4c1f674.png)

**Comment by enriquetuya** [comment]
@redhog Leaflet sample loading CartoDB layers: http://bl.ocks.org/javisantana/fa6ac10bcaff82f1921b

**Comment by redhog** [comment]
http://ivansanchez.github.io/leaflet-vs-openlayers-slides/

**Comment by redhog** [comment]
http://openlayers.org/en/latest/examples/cartodb.html
