### ISSUE TITLE
Safari 9 issues with CORS and redirections

### ISSUE THREAD

**Issue by andres-arana** [GlobalFishingWatch/pelagos-client#89]
On safari 9, CORS headers are not processed on 302 redirect requests. See #739.

This ticket is to revisit the issue once we start using authenticated requests on tiles, because there shouldn't be any more 302 redirect on AJAX requests after that.

**Comment by redhog** [comment]
This is not true, unless we also serve the client files (HTML, JavaScript, CSS) from GAE. Currently the client is loaded from GCS, and CORS occurs when accessing GAE.

**Comment by pwoods25443** [comment]
We can certainly serve everything from GAE.  We only started serving the client form GCS because dojo had more than 10,000 files in it, which exceeds the GAE limit.

**Comment by redhog** [comment]
GCS is also much much faster than GAE...

**Comment by enriquetuya** [comment]
Closing, following this issue here https://github.com/SkyTruth/pelagos-server/issues/1018
